on:
  workflow_dispatch:
  push:
    branches:
      - main

name: "Bump dev version"

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Bump dev version
      uses: DanChaltiel/actions/bump-dev-version@v3
      with:
        create-tag: 'true'
        update-readme: 'true'
